---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: tinyllama-1b-cpu
    serving.kserve.io/deploymentMode: RawDeployment
  name: tinyllama-1b-cpu
  labels:
    opendatahub.io/dashboard: 'true'
    networking.knative.dev/visibility: cluster-local
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '8'
          memory: 8Gi
        requests:
          cpu: '2'
          memory: 4Gi
      runtime: vllm-cpu
      storageUri: 'oci://quay.io/rh-aiservices-bu/tinyllama:1.0'
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: tinyllama-1b-cpu
spec:
  to:
    kind: Service
    name: tinyllama-1b-cpu-predictor
    weight: 100
  port:
    targetPort: tinyllama-1b-cpu-predictor
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
