apiVersion: v2
name: llama-stack-mcp
description: Complete Llama Stack with MCP Server deployment including Llama 3.2-3B, HR API, and all MCP servers
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - llama-stack
  - mcp
  - ai
  - hr-api
  - vllm
home: https://github.com/company/llama-stack-mcp-server
sources:
  - https://github.com/company/llama-stack-mcp-server
maintainers:
  - name: AI Engineering Team
    email: ai-engineering@company.com
annotations:
  category: AI Applications
  openshift.io/display-name: "Llama Stack with MCP Servers"
  openshift.io/provider-display-name: "AI Engineering Team"
  openshift.io/documentation-url: "https://docs.company.com/llama-stack-mcp"
  openshift.io/support-url: "https://support.company.com"

dependencies:
  - name: llama3-2-3b
    version: "1.0.0"
    repository: "file://../llama3.2-3b"
    condition: components.llama3-2-3b.enabled
  - name: llama-stack
    version: "1.0.0"
    repository: "file://../llama-stack"
    condition: components.llama-stack.enabled
  - name: mcp-weather
    version: "1.0.0"
    repository: "file://../mcp-weather"
    condition: components.mcp-weather.enabled
  - name: llama-stack-playground
    version: "1.0.0"
    repository: "file://../llama-stack-playground"
    condition: components.llama-stack-playground.enabled
  - name: hr-enterprise-api
    version: "1.0.0"
    repository: "file://../hr-api"
    condition: components.hr-enterprise-api.enabled
  - name: custom-mcp-server
    version: "1.0.0"
    repository: "file://../custom-mcp-server"
    condition: components.custom-mcp-server.enabled