name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout submodules 
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
          
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install mkdocs-material~=9.5.17 cairosvg~=2.7.1 pillow~=10.3.0
      - run: mkdocs gh-deploy --force
