# This is a basic workflow to help you get started with Actions

name: extract-ai-kickstart-readmes

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  extract-readmes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch READMEs from rh-ai-kickstart
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p docs/kickstart   
          repos=$(gh api orgs/rh-ai-kickstart/repos --paginate -q '.[].name')
          for repo in $repos; do
            git clone https://github.com/rh-ai-kickstart/$repo temp-$repo
            
            mkdir -p docs/kickstart/$repo/
            
            # find README file in root directory
            readme=$(find temp-$repo -maxdepth 1 -type f -iname "readme*")

            # find the first, and only one, directory called image*
            image_dir=$(find temp-$repo -type d -iname "image*" -print -quit)
            
            
            if [ -f "$readme" ]; then
              cp "$readme" docs/kickstart/$repo/
              echo "✓ Extracted README from $repo"
              
              if [ -d "$image_dir" ]; then 
                image_rel_path=${image_dir#temp-$repo}
                mkdir -p docs/kickstart/$repo/$image_rel_path
                cp -R $image_dir/ docs/kickstart/$repo/$image_rel_path/
                echo "✓ Extracted IMAGES from $repo"  
              else 
                echo "⚠ No IMAGES found for $repo"
              fi 
          
            else
              echo "⚠ No README found for $repo"
            fi

            rm -rf temp-$repo
          done

          git config user.name "GitHub Actions Bot" 
          git config user.email "<>"

      - name: Create Pull Request to main 
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          title: "Update kickstart READMEs from rh-ai-kickstart" 
          body: "This PR contains updated README files extracted from all rh-ai-kickstart repositories" 
          base: main
          branch: update-rh-ai-kickstart-readmes
          commit-message: "Update kickstart READMES"
          reviewers: keklundrh
